### ISSUE TITLE
[DEV] Move tests to dedicated folder

### ISSUE THREAD

**Issue by EmanuelSommer** [DataScience-LMU/osis_python_repro#2]
## Goal

Move the tests to a dedicated folder. This is cleaner.

## TODO

- [ ] port the tests themselves
- [ ] update readme to run the tests
- [ ] update CI/CD Workflow to run the tests correctly
